### ISSUE TITLE
5-way switches recommendation

### ISSUE THREAD

**Issue by nweldev** [Painterman/Cardinal#2]
In README:

> SKRHACE010 are rated for more uses, I’m using SKRHABE010, rated for 1/5 the cycles and less expensive, here is the dataset : [SKRHA](https://www.mouser.es/datasheet/2/15/SKRH-1370966.pdf)

Based on this dataset, you might prefer to recommend SKRHA**D**E010 instead of SKRHA**C**E010, as it has guide bosses (like the SKRHABE010 you are using)

Thanks a lot for this project :clap:

**Comment by Painterman** [comment]
Hey, thanks for pointing out, dindt notice at first.

Glad you enjoy the project :D
